name: Test

on:
  push:
    branches: [ main ]
    paths:
    - src/**
    - tests/**
    - pyproject.toml
    - .github/workflows/test.yaml
  pull_request:
    branches: [ main ]
    paths:
    - src/**
    - tests/**
    - pyproject.toml
    - .github/workflows/test.yaml
  workflow_dispatch: {}
  schedule:
  - cron: "40 12 * * 1-5"

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.x
    - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
    - name: Lint and type check
      run: |
        uvx tox -m lint

  test:
    name: Pytest (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.python-version == '3.13' || matrix.python-version == '3.14' }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
        - "3.15"
        - "pypy3.11"
        include:
        - python-version: "3.7"
          os: "ubuntu-22.04"
        - python-version: "3.14"
          os: "windows-latest"
        - python-version: "3.14"
          os: "macos-latest"
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      id: setup-python
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - run: pip install .
    - run: python -Im unittest -v
